name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Executa diariamente à meia-noite UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Debug Info
        run: |
          echo "Running on: ${{ github.event_name }}"
          echo "GitHub User: RIGUETE-PEDRO"

      - uses: Platane/snk@latest  # Usando a versão mais recente
        with:
          github_user_name: RIGUETE-PEDRO
          output: dist/snake.svg
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}  # Usando o token de acesso pessoal

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
